/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const closeToast: typeof import('vant/es')['closeToast']
  const showFailToast: typeof import('vant/es')['showFailToast']
}
